[package]
name = "fs_utilities"
version = "0.1.0"
authors = ["pkart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono="0.4.19"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0"
